### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by zeffo** [Arnva/lets-game-#2]
Hello, this library does not work. Minimal reproducible example:
```py
HELLO today we are BIG, ☺
hoya heya 
```

Error:
![image](https://user-images.githubusercontent.com/43495198/169707263-c7f4b91b-3b57-44c4-bd1e-eeb2134ebc21.png)

How can I solve this?

**Comment by Arnva** [comment]
pls refer my video 

https://user-images.githubusercontent.com/75409785/169707398-b40e1730-8882-4050-b7db-60bcdd535e8b.mp4
